// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubefs/cubefs/blobstore/clustermgr/configmgr (interfaces: ConfigMgrAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfigMgrAPI is a mock of ConfigMgrAPI interface.
type MockConfigMgrAPI struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMgrAPIMockRecorder
}

// MockConfigMgrAPIMockRecorder is the mock recorder for MockConfigMgrAPI.
type MockConfigMgrAPIMockRecorder struct {
	mock *MockConfigMgrAPI
}

// NewMockConfigMgrAPI creates a new mock instance.
func NewMockConfigMgrAPI(ctrl *gomock.Controller) *MockConfigMgrAPI {
	mock := &MockConfigMgrAPI{ctrl: ctrl}
	mock.recorder = &MockConfigMgrAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigMgrAPI) EXPECT() *MockConfigMgrAPIMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockConfigMgrAPI) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConfigMgrAPIMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConfigMgrAPI)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockConfigMgrAPI) Get(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigMgrAPIMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigMgrAPI)(nil).Get), arg0, arg1)
}

// Set mocks base method.
func (m *MockConfigMgrAPI) Set(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockConfigMgrAPIMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockConfigMgrAPI)(nil).Set), arg0, arg1, arg2)
}
