FROM golang:1.17

ENV LTP_VERSION=20210121
ENV LTP_SOURCE=https://github.com/linux-test-project/ltp/archive/${LTP_VERSION}.tar.gz

# intall rocksdb, LTP and replace original version golang with alternative version
RUN     apt-get update && \
        apt-get -y install git gcc make && \
        apt-get -y install libz-dev libbz2-dev libsnappy-dev && \
        apt-get -y install librocksdb-dev && \
        cd /opt > /dev/null && \
        wget "https://storage.jd.local/dpgimage/cfs_spark/myy/client_upgrade/go-1.17.3-alternative.tar.gz" -O /opt/go-1.17.3-alternative.tar.gz && \
        tar zxf go-1.17.3-alternative.tar.gz && \
        rm /opt/go-1.17.3-alternative.tar.gz && \
        rm -rf /usr/local/go && \
        mv /opt/go-1.17.3-alternative /usr/local/go && \
        mkdir -p /tmp/ltp /opt/ltp && cd /tmp/ltp && \
        apt-get install -y xz-utils make gcc flex bison automake autoconf && \
        wget --no-check-certificate ${LTP_SOURCE} && tar xf ${LTP_VERSION}.tar.gz && cd ltp-${LTP_VERSION} && \
        make autotools && ./configure && \
        make -j "$(getconf _NPROCESSORS_ONLN)" all && make install && \
        rm -rf /tmp/ltp && \
        cd / && \
        apt-get install -y sudo python3 python3-pip && \
        pip3 install boto3 unittest2 requests && \
        apt-get install -y jq fuse && \
        apt-get clean
