#ifndef BLOBSTORE_ERRNO_H
#define BLOBSTORE_ERRNO_H

#include <stdint.h>
#include <errno.h>
#include <string.h>

// Success code
#define BS_ERR_OK 0

// Standard Errors and HTTP Status codes are not explicitly defined here.
// Use standard errno and HTTP Status values directly.
// HTTP status codes as registered with IANA.
// See: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

// BlobStore's status codes
// ref: blobstore/common/errors
// Rule: CodeAbcEfg => BS_ERR_ABC_EFG

// access
#define BS_ERR_ACCESS_READ_REQUEST_BODY 466
#define BS_ERR_ACCESS_UNEXPECT 550
#define BS_ERR_ACCESS_SERVICE_DISCOVERY 551
#define BS_ERR_ACCESS_LIMITED 429
#define BS_ERR_ACCESS_EXCEED_SIZE 400

// blobnode
#define BS_ERR_INVALID_PARAM 600
#define BS_ERR_ALREADY_EXIST 601
#define BS_ERR_OUT_OF_LIMIT 602
#define BS_ERR_INTERNAL 603
#define BS_ERR_OVERLOAD 604
#define BS_ERR_PATH_NOT_EXIST 605
#define BS_ERR_PATH_NOT_EMPTY 606
#define BS_ERR_PATH_FIND_ONLINE 607

#define BS_ERR_DISK_NOT_FOUND 611
#define BS_ERR_DISK_BROKEN 613
#define BS_ERR_INVALID_DISK_ID 614
#define BS_ERR_DISK_NO_SPACE 615

#define BS_ERR_VUID_NOT_FOUND 621
#define BS_ERR_VUID_READONLY 622
#define BS_ERR_VUID_RELEASE 623
#define BS_ERR_VUID_NOT_MATCH 624
#define BS_ERR_CHUNK_NOT_READONLY 625
#define BS_ERR_CHUNK_NOT_NORMAL 626
#define BS_ERR_CHUNK_NO_SPACE 627
#define BS_ERR_CHUNK_COMPACTING 628
#define BS_ERR_INVALID_CHUNK_ID 630
#define BS_ERR_TOO_MANY_CHUNKS 632
#define BS_ERR_CHUNK_INUSE 633
#define BS_ERR_SIZE_OVER_BURST 634

#define BS_ERR_BID_NOT_FOUND 651
#define BS_ERR_SHARD_SIZE_TOO_LARGE 652
#define BS_ERR_SHARD_NOT_MARK_DELETE 653
#define BS_ERR_SHARD_MARK_DELETED 654
#define BS_ERR_SHARD_INVALID_OFFSET 655
#define BS_ERR_SHARD_LIST_EXCEED_LIMIT 656
#define BS_ERR_SHARD_INVALID_BID 657

#define BS_ERR_DEST_REPLICA_BAD 670
#define BS_ERR_ORPHAN_SHARD 671
#define BS_ERR_ILLEGAL_TASK 672
#define BS_ERR_REQUEST_LIMITED 673
#define BS_ERR_UNSUPPORTED_TASK_CODE_MODE 674
#define BS_ERR_PUT_SHARD_TIMEOUT 675

// scheduler
#define BS_ERR_NOTHING_TODO 700
#define BS_ERR_UPDATE_VOL_CACHE_FREQ 701

// proxy
#define BS_ERR_NO_CODEMODE_VOLUME 801
#define BS_ERR_ALLOC_BID_FROM_CM 802
#define BS_ERR_CLUSTER_ID_NOT_MATCH 803

// clustermgr
#define BS_ERR_CM_UNEXPECT 900
#define BS_ERR_LOCK_NOT_ALLOW 902
#define BS_ERR_UNLOCK_NOT_ALLOW 903
#define BS_ERR_VOLUME_NOT_EXIST 904
#define BS_ERR_RAFT_PROPOSE 906
#define BS_ERR_NO_LEADER 907
#define BS_ERR_RAFT_READ_INDEX 908
#define BS_ERR_DUPLICATED_MEMBER_INFO 910
#define BS_ERR_CM_DISK_NOT_FOUND 911
#define BS_ERR_INVALID_DISK_STATUS 912
#define BS_ERR_CHANGE_DISK_STATUS_NOT_ALLOW 913
#define BS_ERR_CONCURRENT_ALLOC_VOLUME_UNIT 914
#define BS_ERR_ALLOC_VOLUME_INVALID_PARAMS 916
#define BS_ERR_NO_AVAILABLE_VOLUME 917
#define BS_ERR_OLD_VUID_NOT_MATCH 918
#define BS_ERR_NEW_VUID_NOT_MATCH 919
#define BS_ERR_NEW_DISK_ID_NOT_MATCH 920
#define BS_ERR_CONFIG_ARGUMENT 921
#define BS_ERR_INVALID_CLUSTER_ID 922
#define BS_ERR_INVALID_IDC 923
#define BS_ERR_VOLUME_UNIT_NOT_EXIST 924
#define BS_ERR_REGISTER_SERVICE_INVALID_PARAMS 925
#define BS_ERR_DISK_ABNORMAL_OR_NOT_READONLY 926
#define BS_ERR_STAT_CHUNK_FAILED 927
#define BS_ERR_INVALID_CODE_MODE 928
#define BS_ERR_RETAIN_VOLUME_NOT_ALLOC 929
#define BS_ERR_DROPPED_DISK_HAS_VOLUME_UNIT 930
#define BS_ERR_NOT_SUPPORT_IDLE 931
#define BS_ERR_DISK_IS_DROPPING 932
#define BS_ERR_REJECT_DELETE_SYSTEM_CONFIG 933
#define BS_ERR_CM_NODE_NOT_FOUND 934
#define BS_ERR_CM_HAS_DISK_NOT_DROPPED_OR_REPAIRED 935
#define BS_ERR_CM_NODE_SET_NOT_FOUND 936

#endif // BLOBSTORE_ERRNO_H