{
 "title": "chubaofs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "cfs" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(go_info{app=~\"$app\"}, cluster)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(go_info{app=~\"$app\", cluster=~\"$cluster\"}, role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(go_info{app=~\"$app\", role=~\"$role\", cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "hostip",
    "label": "Host",
    "query": "label_values(go_info{instance=~\"$instance\", cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "master_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"master\"})"
    }
   ]
  },
  {
   "title": "metanode_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"metanode\"})"
    }
   ]
  },
  {
   "title": "datanode_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"dataNode\"})"
    }
   ]
  },
  {
   "title": "client_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"fuseclient\"})"
    }
   ]
  },
  {
   "title": "vol_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum([[app]]_master_vol_count{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "datanode_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_master_dataNodes_total_GB{cluster=~\"$cluster\"})",
     "legendFormat": "total_GB"
    },
    {
     "expr": "sum([[app]]_master_dataNodes_used_GB{cluster=~\"$cluster\"})",
     "legendFormat": "used_GB"
    },
    {
     "expr": "sum([[app]]_master_dataNodes_increased_GB{cluster=~\"$cluster\"})",
     "legendFormat": "increased_GB"
    }
   ]
  },
  {
   "title": "metanode_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_master_metaNodes_total_GB{cluster=~\"$cluster\"})",
     "legendFormat": "total_GB"
    },
    {
     "expr": "sum([[app]]_master_metaNodes_used_GB{cluster=~\"$cluster\"})",
     "legendFormat": "used_GB"
    },
    {
     "expr": "sum([[app]]_master_metaNodes_increased_GB{cluster=~\"$cluster\"})",
     "legendFormat": "increased_GB"
    }
   ]
  },
  {
   "title": "cluster_go_memstats_rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "alloc_bytes_rate"
    }
   ]
  },
  {
   "title": "metanode_OpMetaPartition",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_metanode_OpCreateMetaPartition{cluster=~\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum([[app]]_metanode_OpLoadMetaPartition{cluster=~\"$cluster\"})",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "metanode_OpMetaInode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_metanode_OpMetaBatchInodeGet{cluster=~\"$cluster\"})",
     "legendFormat": "BatchGet"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaCreateInode{cluster=~\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaDeleteInode{cluster=~\"$cluster\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaEvictInode{cluster=~\"$cluster\"})",
     "legendFormat": "Evict"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaInodeGet{cluster=~\"$cluster\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaLinkInode{cluster=~\"$cluster\"})",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "title": "vol_count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_master_vol_count{cluster=~\"$cluster\"})",
     "legendFormat": "vol_count"
    }
   ]
  },
  {
   "title": "metanode_OpMeta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_metanode_OpMetaOpen{cluster=~\"$cluster\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaLookup{cluster=~\"$cluster\"})",
     "legendFormat": "Lookup"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaNodeHeartbeat{cluster=~\"$cluster\"})",
     "legendFormat": "NodeHeartbeat"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaReadDir{cluster=~\"$cluster\"})",
     "legendFormat": "ReadDir"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaReleaseOpen{cluster=~\"$cluster\"})",
     "legendFormat": "ReleaseOpen"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaSetattr{cluster=~\"$cluster\"})",
     "legendFormat": "Setattr"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaTruncate{cluster=~\"$cluster\"})",
     "legendFormat": "Truncate"
    },
    {
     "expr": "sum([[app]]_metanode_writeExtentsFile{cluster=~\"$cluster\"})",
     "legendFormat": "writeExtentFile"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaExtentsList{cluster=~\"$cluster\"})",
     "legendFormat": "GetExtents"
    }
   ]
  },
  {
   "title": "metanode_OpMeta_QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaOpen_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaLookup_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Lookup"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaNodeHeartbeat_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "NodeHeartbeat"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaReadDir_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "ReadDir"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaReleaseOpen_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "ReleaseOpen"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaSetattr_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Setattr"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaTruncate_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "Truncate"
    },
    {
     "expr": "sum(rate([[app]]_metanode_writeExtentsFile_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "writeExtentFile"
    },
    {
     "expr": "sum(rate([[app]]_metanode_OpMetaExtentsList_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "ExtentsList"
    }
   ]
  },
  {
   "title": "vol_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "[[app]]_master_vol_total_GB{cluster=~\"$cluster\"}",
     "legendFormat": "total_{{volName}}"
    },
    {
     "expr": "[[app]]_master_vol_used_GB{cluster=~\"$cluster\"}",
     "legendFormat": "used_{{volName}}"
    },
    {
     "expr": "[[app]]_master_vol_usage_ratio{cluster=~\"$cluster\"}",
     "legendFormat": "usage_ratio_{{volName}}"
    }
   ]
  },
  {
   "title": "metanode_OpMetaDentry",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_metanode_OpMetaCreateDentry{cluster=~\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaDeleteDentry{cluster=~\"$cluster\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum([[app]]_metanode_OpMetaUpdateDentry{cluster=~\"$cluster\"})",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "datanode_Op",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_dataNode_OpLoadDataPartition{cluster=~\"$cluster\"})",
     "legendFormat": "OpLoadDataPartition"
    },
    {
     "expr": "sum([[app]]_dataNode_OpDataNodeHeartbeat{cluster=~\"$cluster\"})",
     "legendFormat": "OpDataNodeHeartbeat"
    },
    {
     "expr": "sum([[app]]_dataNode_OpGetPartitionSize{cluster=~\"$cluster\"})",
     "legendFormat": "OpGetPartitionSize"
    },
    {
     "expr": "sum([[app]]_dataNode_OpGetAppliedId{cluster=~\"$cluster\"})",
     "legendFormat": "OpGetAppliedId"
    },
    {
     "expr": "sum([[app]]_dataNode_OpCreateDataPartition{cluster=~\"$cluster\"})",
     "legendFormat": "OpCreateDataPartition"
    }
   ]
  },
  {
   "title": "datanode_Op_QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate([[app]]_dataNode_OpLoadDataPartition_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "OpLoadDataPartition"
    },
    {
     "expr": "sum(rate([[app]]_dataNode_OpDataNodeHeartbeat_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "OpDataNodeHeartbeat"
    },
    {
     "expr": "sum(rate([[app]]_dataNode_OpGetPartitionSize_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "OpGetPartitionSize"
    },
    {
     "expr": "sum(rate([[app]]_dataNode_OpGetAppliedId_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "OpGetAppliedId"
    },
    {
     "expr": "sum(rate([[app]]_dataNode_NotifyReplicasToRepair_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "NotifyReplicasToRepair"
    },
    {
     "expr": "sum(rate([[app]]_dataNode_streamGetAllWatermarks_count{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "streamGetAllWatermarks"
    }
   ]
  },
  {
   "title": "alarm",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rate([[app]]_master_[[cluster]]_master_alarm{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "master"
    },
    {
     "expr": "sum(rate([[app]]_fuseclient_[[cluster]]_client_alarm{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "client"
    },
    {
     "expr": "sum(rate([[app]]_metanode__alarm{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "metanode"
    },
    {
     "expr": "sum(rate([[app]]_dataNode_dataNode_alarm{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "dataNode"
    },
    {
     "expr": "sum(rate([[app]]_master_[[cluster]]_master_sendTask_alarm{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "sendTask"
    }
   ]
  },
  {
   "title": "datanode_Extent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_dataNode_OpExtentRepairRead{cluster=~\"$cluster\"})",
     "legendFormat": "ExtentRepairRead"
    },
    {
     "expr": "sum([[app]]_dataNode_OpGetAllWatermarks{cluster=~\"$cluster\"})",
     "legendFormat": "GetAllWatermark"
    },
    {
     "expr": "sum([[app]]_dataNode_OpNotifyReplicasToRepair{cluster=~\"$cluster\"})",
     "legendFormat": "OpNotifyReplicasToRepair"
    }
   ]
  },
  {
   "title": "datanode_CreateFile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum([[app]]_dataNode_OpCreateExtent{cluster=~\"$cluster\"})",
     "legendFormat": "CreateExtent"
    },
    {
     "expr": "sum([[app]]_dataNode_OpMarkDelete{cluster=~\"$cluster\"})",
     "legendFormat": "MarkDelete"
    },
    {
     "expr": "sum([[app]]_dataNode_OpCreateDataPartition{cluster=~\"$cluster\"})",
     "legendFormat": "CreateDataPartition"
    },
    {
     "expr": "sum([[app]]_dataNode_OpRandomWrite{cluster=~\"$cluster\"})",
     "legendFormat": "OpRandomWrite"
    }
   ]
  },
  { "title": "GoRuntime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "go info",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go_goroutines"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go_threads"
    }
   ]
  },
  {
   "title": "go_memstats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "alloc_bytes"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "alloc_bytes_total"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\"}",
     "legendFormat": "mallocs_total"
    },
    {
     "expr": "go_memstats_frees_total{instance=~\"$instance\"}",
     "legendFormat": "frees_total"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "other_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mcache_sys_bytes"
    }
   ]
  },
  {
   "title": "gc_duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "seconds_{{quantile}}"
    },
    {
     "expr": "rate(go_gc_duration_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "gc_rate"
    }
   ]
  },
  {
   "title": "process_start_time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 37 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "process_memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident_memory_bytes"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "virtual_memory_bytes"
    },
    {
     "expr": "process_virtual_memory_max_bytes{instance=~\"$instance\"}",
     "legendFormat": "virtual_memory_max_bytes"
    }
   ]
  },
  {
   "title": "process_fd",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 43 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "open_fds"
    },
    {
     "expr": "process_max_fds{instance=~\"$instance\"}",
     "legendFormat": "max_fds"
    }
   ]
  },
  {
   "title": "process_cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "cpu_seconds"
    }
   ]
  },
  { "title": "Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "node_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count(process_start_time_seconds{cluster=~\"$cluster\", role=~\"master\"})",
     "legendFormat": "master"
    },
    {
     "expr": "sum([[app]]_master_metaNodes_count{cluster=~\"$cluster\"})",
     "legendFormat": "metaNode"
    },
    {
     "expr": "sum([[app]]_master_dataNodes_count{cluster=~\"$cluster\"})",
     "legendFormat": "datanode"
    }
   ]
  },
  { "title": "Metanode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "metanode_OpMetaPartition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "[[app]]_metanode_OpCreateMetaPartition{instance=~\"$instance\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "[[app]]_metanode_OpLoadMetaPartition{instance=~\"$instance\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "metanode_OpMetaInode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "[[app]]_metanode_OpMetaBatchInodeGet{instance=~\"$instance\"}",
     "legendFormat": "BatchGet"
    },
    {
     "expr": "[[app]]_metanode_OpMetaCreateInode{instance=~\"$instance\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "[[app]]_metanode_OpMetaDeleteInode{instance=~\"$instance\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "[[app]]_metanode_OpMetaEvictInode{instance=~\"$instance\"}",
     "legendFormat": "Evict"
    },
    {
     "expr": "[[app]]_metanode_OpMetaInodeGet{instance=~\"$instance\"}",
     "legendFormat": "Get"
    },
    {
     "expr": "[[app]]_metanode_OpMetaLinkInode{instance=~\"$instance\"}",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "title": "metanode_OpMetaDentry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "[[app]]_metanode_OpMetaCreateDentry{role=\"$role\",instance=~\"$instance\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "[[app]]_metanode_OpMetaDeleteDentry{role=\"$role\",instance=~\"$instance\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "[[app]]_metanode_OpMetaUpdateDentry{role=\"$role\",instance=~\"$instance\"}",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "metanode_OpMeta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "[[app]]_metanode_OpMetaOpen{instance=~\"$instance\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "[[app]]_metanode_OpMetaLookup{instance=~\"$instance\"}",
     "legendFormat": "Lookup"
    },
    {
     "expr": "[[app]]_metanode_OpMetaNodeHeartbeat{instance=~\"$instance\"}",
     "legendFormat": "NodeHeartbeat"
    },
    {
     "expr": "[[app]]_metanode_OpMetaReadDir{instance=~\"$instance\"}",
     "legendFormat": "ReadDir"
    },
    {
     "expr": "[[app]]_metanode_OpMetaReleaseOpen{instance=~\"$instance\"}",
     "legendFormat": "ReleaseOpen"
    },
    {
     "expr": "[[app]]_metanode_OpMetaSetattr{instance=~\"$instance\"}",
     "legendFormat": "Setattr"
    },
    {
     "expr": "[[app]]_metanode_OpMetaTruncate{instance=~\"$instance\"}",
     "legendFormat": "Truncate"
    }
   ]
  },
  {
   "title": "metanode_OpMetaExtents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "[[app]]_metanode_OpMetaExtentsAdd{instance=~\"$instance\"}",
     "legendFormat": "Add"
    },
    {
     "expr": "[[app]]_metanode_OpMetaExtentsList{instance=~\"$instance\"}",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "metanode_OpMetaExtents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "[[app]]_master_cbasedefault_master_alarm{instance=~\"$instance\"}",
     "legendFormat": "Add"
    },
    {
     "expr": "[[app]]_metanode_OpMetaExtentsList{instance=~\"$instance\"}",
     "legendFormat": "List"
    }
   ]
  },
  {
   "title": "Datanode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "datanode_OpTPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_dataNode_OpBroadcastMinAppliedID{instance=~\"$instance\"}",
       "legendFormat": "BroadcastMinAppliedID"
      },
      {
       "expr": "[[app]]_dataNode_OpCreateDataPartition{instance=~\"$instance\"}",
       "legendFormat": "CreateDataPartition"
      },
      {
       "expr": "[[app]]_dataNode_OpDataNodeHeartbeat{instance=~\"$instance\"}",
       "legendFormat": "DataNodeHeartbeat"
      },
      {
       "expr": "[[app]]_dataNode_OpDecommissionDataPartition{instance=~\"$instance\"}",
       "legendFormat": "DecommissionDataPartition"
      },
      {
       "expr": "[[app]]_dataNode_OpGetAllWatermarks{instance=~\"$instance\"}",
       "legendFormat": "GetAllWatermarks"
      },
      {
       "expr": "[[app]]_dataNode_OpGetAppliedId{instance=~\"$instance\"}",
       "legendFormat": "GetAppliedId"
      },
      {
       "expr": "[[app]]_dataNode_OpGetPartitionSize{instance=~\"$instance\"}",
       "legendFormat": "GetPartitionSize"
      },
      {
       "expr": "[[app]]_dataNode_OpLoadDataPartition{instance=~\"$instance\"}",
       "legendFormat": "LoadDataPartition"
      },
      {
       "expr": "[[app]]_dataNode_OpMarkDelete{instance=~\"$instance\"}",
       "legendFormat": "MarkDelete"
      },
      {
       "expr": "[[app]]_dataNode_OpNotifyReplicasToRepair{instance=~\"$instance\"}",
       "legendFormat": "NotifyReplicasToRepair"
      },
      {
       "expr": "[[app]]_dataNode_OpRandomWrite{instance=~\"$instance\"}",
       "legendFormat": "OpRandomWrite"
      },
      {
       "expr": "[[app]]_dataNode_OpReadTinyDelete{instance=~\"$instance\"}",
       "legendFormat": "ReadTinyDelete"
      },
      {
       "expr": "[[app]]_dataNode_OpStreamRead{instance=~\"$instance\"}",
       "legendFormat": "StreamRead"
      },
      {
       "expr": "[[app]]_dataNode_OpWrite{instance=~\"$instance\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "[[app]]_dataNode_OpCreateExtent{instance=~\"$instance\"}",
       "legendFormat": "CreateExtent"
      },
      {
       "expr": "[[app]]_dataNode_OpExtentRepairRead{instance=~\"$instance\"}",
       "legendFormat": "ExtentRepairdRead"
      }
     ]
    },
    {
     "title": "datanode_OpOPs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate([[app]]_dataNode_OpBroadcastMinAppliedID{instance=~\"$instance\"}[1m])",
       "legendFormat": "BroadcastMinAppliedID"
      },
      {
       "expr": "rate([[app]]_dataNode_OpCreateDataPartition{instance=~\"$instance\"}[1m])",
       "legendFormat": "CreateDataPartition"
      },
      {
       "expr": "rate([[app]]_dataNode_OpDataNodeHeartbeat{instance=~\"$instance\"}[1m])",
       "legendFormat": "DataNodeHeartbeat"
      },
      {
       "expr": "rate([[app]]_dataNode_OpDecommissionDataPartition{instance=~\"$instance\"}[1m])",
       "legendFormat": "DecommissionDataPartition"
      },
      {
       "expr": "rate([[app]]_dataNode_OpGetAllWatermarks{instance=~\"$instance\"}[1m])",
       "legendFormat": "GetAllWatermarks"
      },
      {
       "expr": "rate([[app]]_dataNode_OpGetAppliedId{instance=~\"$instance\"}[1m])",
       "legendFormat": "GetAppliedId"
      },
      {
       "expr": "rate([[app]]_dataNode_OpGetPartitionSize{instance=~\"$instance\"}[1m])",
       "legendFormat": "GetPartitionSize"
      },
      {
       "expr": "rate([[app]]_dataNode_OpLoadDataPartition{instance=~\"$instance\"}[1m])",
       "legendFormat": "LoadDataPartition"
      },
      {
       "expr": "rate([[app]]_dataNode_OpMarkDelete{instance=~\"$instance\"}[1m])",
       "legendFormat": "MarkDelete"
      },
      {
       "expr": "rate([[app]]_dataNode_OpNotifyReplicasToRepair{instance=~\"$instance\"}[1m])",
       "legendFormat": "NotifyReplicasToRepair"
      },
      {
       "expr": "rate([[app]]_dataNode_OpRandomWrite{instance=~\"$instance\"}[1m])",
       "legendFormat": "OpRandomWrite"
      },
      {
       "expr": "rate([[app]]_dataNode_OpReadTinyDelete{instance=~\"$instance\"}[1m])",
       "legendFormat": "ReadTinyDelete"
      },
      {
       "expr": "rate([[app]]_dataNode_OpStreamRead{instance=~\"$instance\"}[1m])",
       "legendFormat": "StreamRead"
      },
      {
       "expr": "rate([[app]]_dataNode_OpWrite{instance=~\"$instance\"}[1m])",
       "legendFormat": "Write"
      },
      {
       "expr": "rate([[app]]_dataNode_OpCreateExtent{instance=~\"$instance\"}[1m])",
       "legendFormat": "CreateExtent"
      },
      {
       "expr": "rate([[app]]_dataNode_OpExtentRepairRead{instance=~\"$instance\"}[1m])",
       "legendFormat": "ExtentRepairdRead"
      }
     ]
    },
    {
     "title": "datanode_Stream",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_dataNode_OpStreamRead{instance=~\"$instance\"}",
       "legendFormat": "StreamRead"
      },
      {
       "expr": "rate([[app]]_dataNode_OpStreamRead_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "StreamRead_ops"
      }
     ]
    },
    {
     "title": "datanode_Extent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_dataNode_OpCreateExtent{instance=~\"$instance\"}",
       "legendFormat": "CreateExtent"
      },
      {
       "expr": "[[app]]_dataNode_OpExtentRepairRead{instance=~\"$instance\"}",
       "legendFormat": "ExtentRepairRead"
      },
      {
       "expr": "rate([[app]]_dataNode_OpCreateExtent_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "CreateExtent_req"
      },
      {
       "expr": "rate([[app]]_dataNode_OpExtentRepairRead{instance=~\"$instance\"}[1m])",
       "legendFormat": "ExtentRepairRead_req"
      }
     ]
    }
   ]
  },
  {
   "title": "FuseClient",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "fuseclient_OpMeta",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_OpMetaOpen{instance=~\"$instance\"}",
       "legendFormat": "MetaOpen"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaReadDir{instance=~\"$instance\"}",
       "legendFormat": "MetaReaddir"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaSetattr{instance=~\"$instance\"}",
       "legendFormat": "MetaSetattr"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaLookup{instance=~\"$instance\"}",
       "legendFormat": "MetaLookup"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaTruncate{instance=~\"$instance\"}",
       "legendFormat": "MetaTruncate"
      }
     ]
    },
    {
     "title": "fuseclient_OpMetaInode",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_OpMetaBatchInodeGet{instance=~\"$instance\"}",
       "legendFormat": "BatchInodeGet"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaCreateInode{instance=~\"$instance\"}",
       "legendFormat": "CreateInode"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaDeleteInode{instance=~\"$instance\"}",
       "legendFormat": "DeleteInode"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaEvictInode{instance=~\"$instance\"}",
       "legendFormat": "EvictInode"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaInodeGet{instance=~\"$instance\"}",
       "legendFormat": "InodeGet"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaTruncate{instance=~\"$instance\"}",
       "legendFormat": "Truncate"
      }
     ]
    },
    {
     "title": "fuseclient_OpMetaDentry",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_OpMetaCreateDentry{instance=~\"$instance\"}",
       "legendFormat": "CreateDentry"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaDeleteDentry{instance=~\"$instance\"}",
       "legendFormat": "DeleteDentry"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaUpdateDentry{instance=~\"$instance\"}",
       "legendFormat": "UpdateDentry"
      }
     ]
    },
    {
     "title": "fuseclient_OpMetaExtent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_OpMetaExtentsAdd{instance=~\"$instance\"}",
       "legendFormat": "AppendExtent"
      },
      {
       "expr": "[[app]]_fuseclient_OpMetaExtentsList{instance=~\"$instance\"}",
       "legendFormat": "GetExtents"
      }
     ]
    },
    {
     "title": "fuseclient_StreamSDK_ops",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate([[app]]_fuseclient_StreamWrite_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "Write"
      },
      {
       "expr": "rate([[app]]_fuseclient_StreamRead_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "ReadCount"
      },
      {
       "expr": "rate([[app]]_fuseclient_StreamSyncWrite_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "SyncWrite"
      },
      {
       "expr": "rate([[app]]_fuseclient_StreamSyncOverwrite_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "SyncOverwrite"
      },
      {
       "expr": "rate([[app]]_fuseclient_StreamOverwrite_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "Overwrite"
      },
      {
       "expr": "rate([[app]]_fuseclient_OpMetaExtentsList_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "GetExtents"
      }
     ]
    },
    {
     "title": "fuseclient_StreamSDK_latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_StreamWrite{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "[[app]]_fuseclient_StreamRead{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "[[app]]_fuseclient_StreamOverwrite{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Overwrite"
      },
      {
       "expr": "[[app]]_fuseclient_StreamCreateExtent{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "CreateExtent"
      },
      {
       "expr": "[[app]]_fuseclient_StreamSyncWrite{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "SyncWrite"
      },
      {
       "expr": "[[app]]_fuseclient_StreamSyncOverwrite{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "SyncOverwrite"
      }
     ]
    },
    {
     "title": "fuseclient_Client_latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_ClientFileWrite{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Write"
      },
      {
       "expr": "[[app]]_fuseclient_ClientFileRead{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "[[app]]_fuseclient_ClientFileRelease{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Release"
      },
      {
       "expr": "[[app]]_fuseclient_ClientFileFsync{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Fsync"
      },
      {
       "expr": "[[app]]_fuseclient_ClientFileOpen{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Open"
      },
      {
       "expr": "[[app]]_fuseclient_ClientFileSetattr{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Setattr"
      },
      {
       "expr": "[[app]]_fuseclient_ClientLookup{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Lookup"
      },
      {
       "expr": "[[app]]_fuseclient_ClientReaddir{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "Readdir"
      },
      {
       "expr": "[[app]]_fuseclient_ClientFileSetattr{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "FileSetattr"
      },
      {
       "expr": "[[app]]_fuseclient_ClientDirSetattr{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "DirSetattr"
      }
     ]
    },
    {
     "title": "fuseclient_Client_ops",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate([[app]]_fuseclient_ClientLookup_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "Lookup"
      },
      {
       "expr": "rate([[app]]_fuseclient_ClientReaddir_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "Readdir"
      },
      {
       "expr": "rate([[app]]_fuseclient_ClientFileSetattr_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "FileSetattr"
      },
      {
       "expr": "rate([[app]]_fuseclient_ClientDirSetattr_count{instance=\"$instance\",cluster=\"$cluster\"}[1m])",
       "legendFormat": "DirSetattr"
      }
     ]
    },
    {
     "title": "ReadPath",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 18 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "[[app]]_fuseclient_FlushInRead{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "FlushInRead"
      },
      {
       "expr": "[[app]]_fuseclient_StreamPrepareReadRequests{instance=~\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "PrepareReadRequest"
      }
     ]
    }
   ]
  }
 ]
}