{
 "title": "cfs-cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "cfs" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(go_info{app=~\"$app\"}, cluster)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(go_info{app=~\"$app\", cluster=~\"$cluster\"}, role)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(go_info{app=~\"$app\", role=~\"$role\", cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "hostip",
    "label": "Host",
    "query": "label_values(go_info{instance=~\"$instance\", cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "master_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"master\"})"
    }
   ]
  },
  {
   "title": "metanode_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"metanode\"})"
    }
   ]
  },
  {
   "title": "datanode_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(go_info{cluster=~\"$cluster\", app=~\"$app\", role=~\"dataNode\"})"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "metanode_OpMetaPartition",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_metanode_OpCreateMetaPartition{cluster=~\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(cfs_metanode_OpLoadMetaPartition{cluster=~\"$cluster\"})",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "metanode_OpMetaInode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_metanode_OpMetaBatchInodeGet{cluster=~\"$cluster\"})",
     "legendFormat": "BatchGet"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaCreateInode{cluster=~\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaDeleteInode{cluster=~\"$cluster\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaEvictInode{cluster=~\"$cluster\"})",
     "legendFormat": "Evict"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaInodeGet{cluster=~\"$cluster\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaLinkInode{cluster=~\"$cluster\"})",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "title": "metanode_OpMetaDentry",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_metanode_OpMetaCreateDentry{cluster=~\"$cluster\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaDeleteDentry{cluster=~\"$cluster\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaUpdateDentry{cluster=~\"$cluster\"})",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "datanode_CreateFile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_CreateFile{cluster=~\"$cluster\"})",
     "legendFormat": "CreateFile"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_MarkDelete{cluster=~\"$cluster\"})",
     "legendFormat": "MarkDelete"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_Read{cluster=~\"$cluster\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_Write{cluster=~\"$cluster\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_RandomWrite{cluster=~\"$cluster\"})",
     "legendFormat": "RandomWrite"
    }
   ]
  },
  {
   "title": "datanode_Op",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_OpLoadDataPartition{cluster=~\"$cluster\"})",
     "legendFormat": "OpLoadDataPartition"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_OpDataNodeHeartbeat{cluster=~\"$cluster\"})",
     "legendFormat": "OpDataNodeHeartbeat"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_OpGetPartitionSize{cluster=~\"$cluster\"})",
     "legendFormat": "OpGetPartitionSize"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_OpGetAppliedId{cluster=~\"$cluster\"})",
     "legendFormat": "OpGetAppliedId"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_OpCreateDataPartition{cluster=~\"$cluster\"})",
     "legendFormat": "OpCreateDataPartition"
    }
   ]
  },
  {
   "title": "metanode_OpMeta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_metanode_OpMetaOpen{cluster=~\"$cluster\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaLookup{cluster=~\"$cluster\"})",
     "legendFormat": "Lookup"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaNodeHeartbeat{cluster=~\"$cluster\"})",
     "legendFormat": "NodeHeartbeat"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaReadDir{cluster=~\"$cluster\"})",
     "legendFormat": "ReadDir"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaReleaseOpen{cluster=~\"$cluster\"})",
     "legendFormat": "ReleaseOpen"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaSetattr{cluster=~\"$cluster\"})",
     "legendFormat": "Setattr"
    },
    {
     "expr": "sum(cfs_metanode_OpMetaTruncate{cluster=~\"$cluster\"})",
     "legendFormat": "Truncate"
    }
   ]
  },
  {
   "title": "datanode_Extent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_ExtentRepairRead{cluster=~\"$cluster\"})",
     "legendFormat": "ExtentRepairRead"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_GetAllExtentWatermark{cluster=~\"$cluster\"})",
     "legendFormat": "GetAllExtentWatermark"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_NotifyExtentRepair{cluster=~\"$cluster\"})",
     "legendFormat": "NotifyExtentRepair"
    }
   ]
  },
  {
   "title": "datanode_Stream",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamRead{cluster=~\"$cluster\"})",
     "legendFormat": "streamRead"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamWrite{cluster=~\"$cluster\"})",
     "legendFormat": "streamWrite"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamCreateFile{cluster=~\"$cluster\"})",
     "legendFormat": "streamCreateFile"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamExtentRepairRead{cluster=~\"$cluster\"})",
     "legendFormat": "streamExtentRepairRead"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamMarkDelete{cluster=~\"$cluster\"})",
     "legendFormat": "streamMarkDelete"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamOpGetAppliedId{cluster=~\"$cluster\"})",
     "legendFormat": "streamOpGetAppliedId"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamOpGetPartitionSize{cluster=~\"$cluster\"})",
     "legendFormat": "streamOpGetPartitionSize"
    },
    {
     "expr": "sum(cfs_dataNode_[[cluster]]_datanode_streamNotifyExtentRepair{cluster=~\"$cluster\"})",
     "legendFormat": "streamNotifyExtentRepair"
    }
   ]
  },
  { "title": "GoRuntime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "go info",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go_goroutines"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go_threads"
    }
   ]
  },
  {
   "title": "go_memstats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "alloc_bytes"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "alloc_bytes_total"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys_bytes"
    }
   ]
  },
  {
   "title": "gc_duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "seconds_{{quantile}}"
    },
    {
     "expr": "rate(go_gc_duration_seconds_count{instance=~\"$instance\"}[1m])",
     "legendFormat": "gc_rate"
    }
   ]
  },
  { "title": "Master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  { "title": "Metanode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "metanode_OpMetaPartition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_metanode_OpCreateMetaPartition{instance=~\"$instance\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "cfs_metanode_OpLoadMetaPartition{instance=~\"$instance\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "metanode_OpMetaInode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_metanode_OpMetaBatchInodeGet{instance=~\"$instance\"}",
     "legendFormat": "BatchGet"
    },
    {
     "expr": "cfs_metanode_OpMetaCreateInode{instance=~\"$instance\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "cfs_metanode_OpMetaDeleteInode{instance=~\"$instance\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "cfs_metanode_OpMetaEvictInode{instance=~\"$instance\"}",
     "legendFormat": "Evict"
    },
    {
     "expr": "cfs_metanode_OpMetaInodeGet{instance=~\"$instance\"}",
     "legendFormat": "Get"
    },
    {
     "expr": "cfs_metanode_OpMetaLinkInode{instance=~\"$instance\"}",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "title": "metanode_OpMetaDentry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_metanode_OpMetaCreateDentry{instance=~\"$instance\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "cfs_metanode_OpMetaDeleteDentry{instance=~\"$instance\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "cfs_metanode_OpMetaUpdateDentry{instance=~\"$instance\"}",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "metanode_OpMeta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_metanode_OpMetaOpen{instance=~\"$instance\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "cfs_metanode_OpMetaLookup{instance=~\"$instance\"}",
     "legendFormat": "Lookup"
    },
    {
     "expr": "cfs_metanode_OpMetaNodeHeartbeat{instance=~\"$instance\"}",
     "legendFormat": "NodeHeartbeat"
    },
    {
     "expr": "cfs_metanode_OpMetaReadDir{instance=~\"$instance\"}",
     "legendFormat": "ReadDir"
    },
    {
     "expr": "cfs_metanode_OpMetaReleaseOpen{instance=~\"$instance\"}",
     "legendFormat": "ReleaseOpen"
    },
    {
     "expr": "cfs_metanode_OpMetaSetattr{instance=~\"$instance\"}",
     "legendFormat": "Setattr"
    },
    {
     "expr": "cfs_metanode_OpMetaTruncate{instance=~\"$instance\"}",
     "legendFormat": "Truncate"
    }
   ]
  },
  {
   "title": "metanode_OpMetaExtents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_metanode_OpMetaExtentsAdd{instance=~\"$instance\"}",
     "legendFormat": "Add"
    },
    {
     "expr": "cfs_metanode_OpMetaExtentsList{instance=~\"$instance\"}",
     "legendFormat": "List"
    }
   ]
  },
  { "title": "Datanode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "datanode_CreateFile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_CreateFile{instance=~\"$instance\"}",
     "legendFormat": "CreateFile"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_MarkDelete{instance=~\"$instance\"}",
     "legendFormat": "MarkDelete"
    }
   ]
  },
  {
   "title": "datanode_Extent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_ExtentRepairRead{instance=~\"$instance\"}",
     "legendFormat": "ExtentRepairRead"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_GetAllExtentWatermark{instance=~\"$instance\"}",
     "legendFormat": "GetAllExtentWatermark"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_NotifyExtentRepair{instance=~\"$instance\"}",
     "legendFormat": "NotifyExtentRepair"
    }
   ]
  },
  {
   "title": "datanode_Op",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_OpLoadDataPartition{instance=~\"$instance\"}",
     "legendFormat": "OpLoadDataPartition"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_OpDataNodeHeartbeat{instance=~\"$instance\"}",
     "legendFormat": "OpDataNodeHeartbeat"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_OpGetPartitionSize{instance=~\"$instance\"}",
     "legendFormat": "OpGetPartitionSize"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_OpGetAppliedId{instance=~\"$instance\"}",
     "legendFormat": "OpGetAppliedId"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_OpCreateDataPartition{instance=~\"$instance\"}",
     "legendFormat": "OpCreateDataPartition"
    }
   ]
  },
  {
   "title": "datanode_IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_Read{instance=~\"$instance\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_Write{instance=~\"$instance\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_RandomWrite{instance=~\"$instance\"}",
     "legendFormat": "RandomWrite"
    }
   ]
  },
  {
   "title": "datanode_Stream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamRead{instance=~\"$instance\"}",
     "legendFormat": "streamRead"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamWrite{instance=~\"$instance\"}",
     "legendFormat": "streamWrite"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamCreateFile{instance=~\"$instance\"}",
     "legendFormat": "streamCreateFile"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamExtentRepairRead{instance=~\"$instance\"}",
     "legendFormat": "streamExtentRepairRead"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamMarkDelete{instance=~\"$instance\"}",
     "legendFormat": "streamMarkDelete"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamOpGetAppliedId{instance=~\"$instance\"}",
     "legendFormat": "streamOpGetAppliedId"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamOpGetPartitionSize{instance=~\"$instance\"}",
     "legendFormat": "streamOpGetPartitionSize"
    },
    {
     "expr": "cfs_dataNode_[[cluster]]_datanode_streamNotifyExtentRepair{instance=~\"$instance\"}",
     "legendFormat": "streamNotifyExtentRepair"
    }
   ]
  },
  {
   "title": "FuseClient",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "fuseclient_OpMeta",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "cfs_fuseclient_OpMetaOpen{instance=~\"$instance\"}",
       "legendFormat": "Open"
      },
      {
       "expr": "cfs_fuseclient_OpMetaExtentsAdd{instance=~\"$instance\"}",
       "legendFormat": "ExtentsAdd"
      },
      {
       "expr": "cfs_fuseclient_OpMetaExtentsList{instance=~\"$instance\"}",
       "legendFormat": "ExtentsList"
      },
      {
       "expr": "cfs_fuseclient_OpMetaReadDir{instance=~\"$instance\"}",
       "legendFormat": "ReadDir"
      },
      {
       "expr": "cfs_fuseclient_OpMetaSetattr{instance=~\"$instance\"}",
       "legendFormat": "Setattr"
      }
     ]
    },
    {
     "title": "fuseclient_OpMetaInode",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 85 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "cfs_fuseclient_OpMetaBatchInodeGet{instance=~\"$instance\"}",
       "legendFormat": "BatchInodeGet"
      },
      {
       "expr": "cfs_fuseclient_OpMetaCreateInode{instance=~\"$instance\"}",
       "legendFormat": "CreateInode"
      },
      {
       "expr": "cfs_fuseclient_OpMetaDeleteInode{instance=~\"$instance\"}",
       "legendFormat": "DeleteInode"
      },
      {
       "expr": "cfs_fuseclient_OpMetaEvictInode{instance=~\"$instance\"}",
       "legendFormat": "EvictInode"
      },
      {
       "expr": "cfs_fuseclient_OpMetaInodeGet{instance=~\"$instance\"}",
       "legendFormat": "InodeGet"
      }
     ]
    },
    {
     "title": "fuseclient_OpMetaDentry",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 14, "y": 85 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "cfs_fuseclient_OpMetaCreateDentry{instance=~\"$instance\"}",
       "legendFormat": "Create"
      },
      {
       "expr": "cfs_fuseclient_OpMetaDeleteDentry{instance=~\"$instance\"}",
       "legendFormat": "Delete"
      }
     ]
    },
    {
     "title": "fuseclient_OpMetaExtent",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "cfs_fuseclient_OpMetaExtentsAdd{instance=~\"$instance\"}",
       "legendFormat": "ExtentsAdd"
      },
      {
       "expr": "cfs_fuseclient_OpMetaExtentsList{instance=~\"$instance\"}",
       "legendFormat": "ExtentsList"
      }
     ]
    }
   ]
  }
 ]
}