// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cubefs/cubefs/blobstore/clustermgr/cluster (interfaces: ShardNodeManagerAPI)

// Package cluster is a generated GoMock package.
package cluster

import (
	context "context"
	reflect "reflect"

	clustermgr "github.com/cubefs/cubefs/blobstore/api/clustermgr"
	proto "github.com/cubefs/cubefs/blobstore/common/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockShardNodeManagerAPI is a mock of ShardNodeManagerAPI interface.
type MockShardNodeManagerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockShardNodeManagerAPIMockRecorder
}

// MockShardNodeManagerAPIMockRecorder is the mock recorder for MockShardNodeManagerAPI.
type MockShardNodeManagerAPIMockRecorder struct {
	mock *MockShardNodeManagerAPI
}

// NewMockShardNodeManagerAPI creates a new mock instance.
func NewMockShardNodeManagerAPI(ctrl *gomock.Controller) *MockShardNodeManagerAPI {
	mock := &MockShardNodeManagerAPI{ctrl: ctrl}
	mock.recorder = &MockShardNodeManagerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShardNodeManagerAPI) EXPECT() *MockShardNodeManagerAPIMockRecorder {
	return m.recorder
}

// AddDisk mocks base method.
func (m *MockShardNodeManagerAPI) AddDisk(arg0 context.Context, arg1 *clustermgr.ShardNodeDiskInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDisk", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDisk indicates an expected call of AddDisk.
func (mr *MockShardNodeManagerAPIMockRecorder) AddDisk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDisk", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).AddDisk), arg0, arg1)
}

// AllocDiskID mocks base method.
func (m *MockShardNodeManagerAPI) AllocDiskID(arg0 context.Context) (proto.DiskID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocDiskID", arg0)
	ret0, _ := ret[0].(proto.DiskID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocDiskID indicates an expected call of AllocDiskID.
func (mr *MockShardNodeManagerAPIMockRecorder) AllocDiskID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocDiskID", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).AllocDiskID), arg0)
}

// AllocNodeID mocks base method.
func (m *MockShardNodeManagerAPI) AllocNodeID(arg0 context.Context) (proto.NodeID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocNodeID", arg0)
	ret0, _ := ret[0].(proto.NodeID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocNodeID indicates an expected call of AllocNodeID.
func (mr *MockShardNodeManagerAPIMockRecorder) AllocNodeID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocNodeID", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).AllocNodeID), arg0)
}

// AllocShards mocks base method.
func (m *MockShardNodeManagerAPI) AllocShards(arg0 context.Context, arg1 AllocShardsPolicy) ([]proto.DiskID, proto.DiskSetID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocShards", arg0, arg1)
	ret0, _ := ret[0].([]proto.DiskID)
	ret1, _ := ret[1].(proto.DiskSetID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AllocShards indicates an expected call of AllocShards.
func (mr *MockShardNodeManagerAPIMockRecorder) AllocShards(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocShards", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).AllocShards), arg0, arg1)
}

// CheckDiskInfoDuplicated mocks base method.
func (m *MockShardNodeManagerAPI) CheckDiskInfoDuplicated(arg0 context.Context, arg1 proto.DiskID, arg2 *clustermgr.DiskInfo, arg3 *clustermgr.NodeInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDiskInfoDuplicated", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDiskInfoDuplicated indicates an expected call of CheckDiskInfoDuplicated.
func (mr *MockShardNodeManagerAPIMockRecorder) CheckDiskInfoDuplicated(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDiskInfoDuplicated", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).CheckDiskInfoDuplicated), arg0, arg1, arg2, arg3)
}

// CheckNodeInfoDuplicated mocks base method.
func (m *MockShardNodeManagerAPI) CheckNodeInfoDuplicated(arg0 context.Context, arg1 *clustermgr.NodeInfo) (proto.NodeID, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNodeInfoDuplicated", arg0, arg1)
	ret0, _ := ret[0].(proto.NodeID)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// CheckNodeInfoDuplicated indicates an expected call of CheckNodeInfoDuplicated.
func (mr *MockShardNodeManagerAPIMockRecorder) CheckNodeInfoDuplicated(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNodeInfoDuplicated", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).CheckNodeInfoDuplicated), arg0, arg1)
}

// GetDiskInfo mocks base method.
func (m *MockShardNodeManagerAPI) GetDiskInfo(arg0 context.Context, arg1 proto.DiskID) (*clustermgr.ShardNodeDiskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiskInfo", arg0, arg1)
	ret0, _ := ret[0].(*clustermgr.ShardNodeDiskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiskInfo indicates an expected call of GetDiskInfo.
func (mr *MockShardNodeManagerAPIMockRecorder) GetDiskInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiskInfo", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).GetDiskInfo), arg0, arg1)
}

// GetHeartbeatChangeDisks mocks base method.
func (m *MockShardNodeManagerAPI) GetHeartbeatChangeDisks() []HeartbeatEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeartbeatChangeDisks")
	ret0, _ := ret[0].([]HeartbeatEvent)
	return ret0
}

// GetHeartbeatChangeDisks indicates an expected call of GetHeartbeatChangeDisks.
func (mr *MockShardNodeManagerAPIMockRecorder) GetHeartbeatChangeDisks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeartbeatChangeDisks", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).GetHeartbeatChangeDisks))
}

// GetNodeInfo mocks base method.
func (m *MockShardNodeManagerAPI) GetNodeInfo(arg0 context.Context, arg1 proto.NodeID) (*clustermgr.ShardNodeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeInfo", arg0, arg1)
	ret0, _ := ret[0].(*clustermgr.ShardNodeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeInfo indicates an expected call of GetNodeInfo.
func (mr *MockShardNodeManagerAPIMockRecorder) GetNodeInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeInfo", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).GetNodeInfo), arg0, arg1)
}

// IsDiskWritable mocks base method.
func (m *MockShardNodeManagerAPI) IsDiskWritable(arg0 context.Context, arg1 proto.DiskID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDiskWritable", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDiskWritable indicates an expected call of IsDiskWritable.
func (mr *MockShardNodeManagerAPIMockRecorder) IsDiskWritable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDiskWritable", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).IsDiskWritable), arg0, arg1)
}

// IsDroppingDisk mocks base method.
func (m *MockShardNodeManagerAPI) IsDroppingDisk(arg0 context.Context, arg1 proto.DiskID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDroppingDisk", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDroppingDisk indicates an expected call of IsDroppingDisk.
func (mr *MockShardNodeManagerAPIMockRecorder) IsDroppingDisk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDroppingDisk", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).IsDroppingDisk), arg0, arg1)
}

// ListDiskInfo mocks base method.
func (m *MockShardNodeManagerAPI) ListDiskInfo(arg0 context.Context, arg1 *clustermgr.ListOptionArgs) ([]*clustermgr.ShardNodeDiskInfo, proto.DiskID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiskInfo", arg0, arg1)
	ret0, _ := ret[0].([]*clustermgr.ShardNodeDiskInfo)
	ret1, _ := ret[1].(proto.DiskID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDiskInfo indicates an expected call of ListDiskInfo.
func (mr *MockShardNodeManagerAPIMockRecorder) ListDiskInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiskInfo", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).ListDiskInfo), arg0, arg1)
}

// ListDroppingDisk mocks base method.
func (m *MockShardNodeManagerAPI) ListDroppingDisk(arg0 context.Context) ([]*clustermgr.ShardNodeDiskInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDroppingDisk", arg0)
	ret0, _ := ret[0].([]*clustermgr.ShardNodeDiskInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDroppingDisk indicates an expected call of ListDroppingDisk.
func (mr *MockShardNodeManagerAPIMockRecorder) ListDroppingDisk(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDroppingDisk", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).ListDroppingDisk), arg0)
}

// RefreshExpireTime mocks base method.
func (m *MockShardNodeManagerAPI) RefreshExpireTime() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshExpireTime")
}

// RefreshExpireTime indicates an expected call of RefreshExpireTime.
func (mr *MockShardNodeManagerAPIMockRecorder) RefreshExpireTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshExpireTime", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).RefreshExpireTime))
}

// SetStatus mocks base method.
func (m *MockShardNodeManagerAPI) SetStatus(arg0 context.Context, arg1 proto.DiskID, arg2 proto.DiskStatus, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockShardNodeManagerAPIMockRecorder) SetStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).SetStatus), arg0, arg1, arg2, arg3)
}

// Stat mocks base method.
func (m *MockShardNodeManagerAPI) Stat(arg0 context.Context, arg1 proto.DiskType) *clustermgr.SpaceStatInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", arg0, arg1)
	ret0, _ := ret[0].(*clustermgr.SpaceStatInfo)
	return ret0
}

// Stat indicates an expected call of Stat.
func (mr *MockShardNodeManagerAPIMockRecorder) Stat(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).Stat), arg0, arg1)
}

// ValidateNodeInfo mocks base method.
func (m *MockShardNodeManagerAPI) ValidateNodeInfo(arg0 context.Context, arg1 *clustermgr.NodeInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateNodeInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateNodeInfo indicates an expected call of ValidateNodeInfo.
func (mr *MockShardNodeManagerAPIMockRecorder) ValidateNodeInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateNodeInfo", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).ValidateNodeInfo), arg0, arg1)
}

// addDiskNoLocked mocks base method.
func (m *MockShardNodeManagerAPI) addDiskNoLocked(arg0 *diskItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addDiskNoLocked", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// addDiskNoLocked indicates an expected call of addDiskNoLocked.
func (mr *MockShardNodeManagerAPIMockRecorder) addDiskNoLocked(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addDiskNoLocked", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).addDiskNoLocked), arg0)
}

// addDroppingDisk mocks base method.
func (m *MockShardNodeManagerAPI) addDroppingDisk(arg0 proto.DiskID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addDroppingDisk", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// addDroppingDisk indicates an expected call of addDroppingDisk.
func (mr *MockShardNodeManagerAPIMockRecorder) addDroppingDisk(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addDroppingDisk", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).addDroppingDisk), arg0)
}

// addDroppingNode mocks base method.
func (m *MockShardNodeManagerAPI) addDroppingNode(arg0 proto.NodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addDroppingNode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// addDroppingNode indicates an expected call of addDroppingNode.
func (mr *MockShardNodeManagerAPIMockRecorder) addDroppingNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addDroppingNode", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).addDroppingNode), arg0)
}

// droppedDisk mocks base method.
func (m *MockShardNodeManagerAPI) droppedDisk(arg0 proto.DiskID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "droppedDisk", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// droppedDisk indicates an expected call of droppedDisk.
func (mr *MockShardNodeManagerAPIMockRecorder) droppedDisk(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "droppedDisk", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).droppedDisk), arg0)
}

// droppedNode mocks base method.
func (m *MockShardNodeManagerAPI) droppedNode(arg0 proto.NodeID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "droppedNode", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// droppedNode indicates an expected call of droppedNode.
func (mr *MockShardNodeManagerAPIMockRecorder) droppedNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "droppedNode", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).droppedNode), arg0)
}

// isDroppingDisk mocks base method.
func (m *MockShardNodeManagerAPI) isDroppingDisk(arg0 proto.DiskID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isDroppingDisk", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// isDroppingDisk indicates an expected call of isDroppingDisk.
func (mr *MockShardNodeManagerAPIMockRecorder) isDroppingDisk(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isDroppingDisk", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).isDroppingDisk), arg0)
}

// isDroppingNode mocks base method.
func (m *MockShardNodeManagerAPI) isDroppingNode(arg0 proto.NodeID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "isDroppingNode", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// isDroppingNode indicates an expected call of isDroppingNode.
func (mr *MockShardNodeManagerAPIMockRecorder) isDroppingNode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isDroppingNode", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).isDroppingNode), arg0)
}

// updateDiskNoLocked mocks base method.
func (m *MockShardNodeManagerAPI) updateDiskNoLocked(arg0 *diskItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateDiskNoLocked", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateDiskNoLocked indicates an expected call of updateDiskNoLocked.
func (mr *MockShardNodeManagerAPIMockRecorder) updateDiskNoLocked(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateDiskNoLocked", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).updateDiskNoLocked), arg0)
}

// updateDiskStatusNoLocked mocks base method.
func (m *MockShardNodeManagerAPI) updateDiskStatusNoLocked(arg0 proto.DiskID, arg1 proto.DiskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateDiskStatusNoLocked", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateDiskStatusNoLocked indicates an expected call of updateDiskStatusNoLocked.
func (mr *MockShardNodeManagerAPIMockRecorder) updateDiskStatusNoLocked(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateDiskStatusNoLocked", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).updateDiskStatusNoLocked), arg0, arg1)
}

// updateNodeNoLocked mocks base method.
func (m *MockShardNodeManagerAPI) updateNodeNoLocked(arg0 *nodeItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateNodeNoLocked", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateNodeNoLocked indicates an expected call of updateNodeNoLocked.
func (mr *MockShardNodeManagerAPIMockRecorder) updateNodeNoLocked(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateNodeNoLocked", reflect.TypeOf((*MockShardNodeManagerAPI)(nil).updateNodeNoLocked), arg0)
}
