name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  GolangTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go Version 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make rocksdb includes
        run: |
          wget -O deps.tar.gz http://ocs-upload-cn.heytapcs.com/deps.tar.gz
          tar -zxf deps.tar.gz
          mv deps .deps
          source env.sh
          echo "CGO_CFLAGS=${CGO_CFLAGS}" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=${CGO_LDFLAGS}" >> $GITHUB_ENV

      - name: Check and Verify Go modules
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          go mod verify

      - name: Go test with coverage
        run: |
          go test -trimpath -covermode=count --coverprofile coverage.txt ./...
        env:
          JENKINS_TEST: TRUE

      - name: Upload codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
