name: BlobStore-Format

on:
  push:
    paths:
        - 'blobstore/**.go'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
        - 'blobstore/**'

jobs:
  GolangFormat:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go Version 1.17.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download rocksdb_libs
        run: |
            pushd build
            wget -O rocksdb_libs.tar.gz https://ocs-cn-north1.heytapcs.com/cubefs/github/ci/rocksdb_libs.tar.gz
            tar -zxvf rocksdb_libs.tar.gz
            . cgo_env.sh
            echo "CGO_CFLAGS=${CGO_CFLAGS}" >> $GITHUB_ENV
            echo "CGO_LDFLAGS=${CGO_LDFLAGS}" >> $GITHUB_ENV
            popd

      - name: Check golang vet
        run: |
          cd blobstore
          go vet -trimpath ./...

      - name: Go code format with gofumpt
        run: |
          cd blobstore
          go install mvdan.cc/gofumpt@v0.2.1
          gofumpt -l -w .
          git diff --exit-code
